### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by dietrichson** [rOpenGov/RPublica#2]
I installed the package and found that the example returns an error.

```
> library('RPublica')
> str(np_search('propublica'), max=1)
Error in ppQuery("search", "https://projects.propublica.org/nonprofits/api/v1/",  : 
  Internal Server Error (HTTP 500).
```

I see that the package is a bit dated, I am happy to update it if you like, since I am working on accessing the campaign finance API.

**Comment by peterhovmand** [comment]
I ran into the same issue running 0.1.3 from CRAN mirror and then reinstalled 0.1.3.9000 from here. 

> str(np_search("propublica"), max = 1)
Error in ppQuery("search", "https://projects.propublica.org/nonprofits/api/v1/",  : 
  Internal Server Error (HTTP 500).

Note that the example, 
> np_org(142007220)
works fine.
